import { DM_COLLECTIONS } from './collections.js';
import { emitNotification } from './notificationService.js';
import { getEligibleBase, sumProjectBillingTotals } from './calculationEngine.js';
import { computeSpvReadinessScore } from './reconciliationService.js';

function num(v) {
  return Number(v) || 0;
}

/**
 * Scan project for governance risks and upsert dm_risk_exceptions.
 * @param {import('mongodb').Db} db
 * @param {string} projectId
 */
export async function scanProjectRisks(db, projectId) {
  const project = await db.collection(DM_COLLECTIONS.projects).findOne({ _id: projectId });
  if (!project) return { risks: [] };

  const risks = [];
  const now = new Date();

  if (!project.activeBillingConfigId) {
    risks.push(risk('billing_no_model', 'high', 'No billing model configured', projectId));
  }

  const spvId = project.spvIds?.[0];
  if (spvId) {
    const spv = await db.collection(DM_COLLECTIONS.spvs).findOne({ _id: spvId });
    if (spv?.agreementStatus !== 'signed') {
      risks.push(risk('billing_no_agreement', 'high', 'DMA / agreement not signed', projectId, spvId));
    }
    const readiness = await computeSpvReadinessScore(db, spvId);
    if (readiness.score < 70) {
      risks.push(risk('compliance_gap', 'medium', `SPV readiness ${readiness.score}% — missing documents`, projectId, spvId));
    }
  }

  const config = project.activeBillingConfigId
    ? await db.collection(DM_COLLECTIONS.billingConfigs).findOne({ _id: project.activeBillingConfigId })
    : null;
  const eligibleBase = getEligibleBase(project, config || {});
  const cap = eligibleBase * (num(config?.dmCapPct ?? project.dmCapPct ?? 10) / 100);
  const totals = await sumProjectBillingTotals(db, projectId);

  if (cap > 0 && totals.dmFeeBilledTtd / cap >= 0.9) {
    risks.push(risk('dm_cap_nearing', totals.dmFeeBilledTtd / cap >= 1 ? 'critical' : 'high', `DM cap ${Math.round((totals.dmFeeBilledTtd / cap) * 100)}% utilised`, projectId));
  }

  if (totals.dmFeeBilledTtd - totals.dmFeePaidTtd > 500000) {
    risks.push(risk('spv_payable_aging', 'medium', 'SPV payable to GA exceeds ₹5L unpaid', projectId));
  }

  if (project.revenueStatus === 'collection_active' && project.collectionsTtd > 0) {
    const lastInvoice = await db
      .collection(DM_COLLECTIONS.invoices)
      .find({ projectId, status: { $nin: ['REJECTED', 'DRAFT'] } })
      .sort({ periodMonth: -1 })
      .limit(1)
      .toArray();
    if (!lastInvoice.length) {
      risks.push(risk('collections_no_billing', 'high', 'Collections active but no DM invoice billed', projectId));
    }
  }

  if (project.revenueStatus === 'pre_revenue') {
    const created = project.createdAt ? new Date(project.createdAt) : now;
    const months = (now - created) / (30 * 24 * 3600 * 1000);
    if (months > 12) {
      risks.push(risk('pre_revenue_extended', 'medium', 'Pre-revenue phase exceeds 12 months', projectId));
    }
  }

  const lastSync = project.integrationSnapshot?.cashflow?.syncedAt;
  if (lastSync) {
    const days = (now - new Date(lastSync)) / (24 * 3600 * 1000);
    if (days > 7) {
      risks.push(risk('sync_stale', 'low', `Cashflow sync stale (${Math.round(days)} days)`, projectId));
    }
  } else {
    risks.push(risk('sync_stale', 'medium', 'Cashflow never synced to DM app', projectId));
  }

  const risksCol = db.collection(DM_COLLECTIONS.riskExceptions);
  await risksCol.deleteMany({ projectId, status: 'open', autoGenerated: true });

  for (const r of risks) {
    const id = `risk_${projectId}_${r.riskType}`;
    await risksCol.updateOne(
      { _id: id },
      {
        $set: {
          ...r,
          _id: id,
          projectId,
          spvId: r.spvId || project.spvIds?.[0] || null,
          status: 'open',
          autoGenerated: true,
          owner: null,
          dueDate: null,
          suggestedAction: suggestAction(r.riskType),
          updatedAt: now
        }
      },
      { upsert: true }
    );
  }

  return { risks, count: risks.length };
}

function risk(type, severity, message, projectId, spvId = null) {
  return {
    riskType: type,
    riskCategory: categoryFor(type),
    severity,
    message,
    projectId,
    spvId
  };
}

function categoryFor(type) {
  if (type.includes('cap')) return 'billing';
  if (type.includes('compliance') || type.includes('agreement')) return 'compliance';
  if (type.includes('sync')) return 'integration';
  if (type.includes('payable')) return 'cashflow';
  return 'governance';
}

function suggestAction(type) {
  const map = {
    billing_no_model: 'Configure hybrid billing model in Billing Models',
    billing_no_agreement: 'Upload signed DMA and update SPV agreement status',
    compliance_gap: 'Complete compliance document checklist',
    dm_cap_nearing: 'Review billing against 10% cap; leadership approval if needed',
    spv_payable_aging: 'Follow up SPV payment or accrue per DMA waterfall',
    collections_no_billing: 'Run billing workspace and generate collection-linked invoice',
    pre_revenue_extended: 'Review retainer economics with leadership',
    sync_stale: 'Run integration sync from project or integrations page'
  };
  return map[type] || 'Review and resolve';
}

/**
 * Detect billing triggers after sync.
 * @param {import('mongodb').Db} db
 * @param {string} projectId
 * @param {object} before
 * @param {object} after
 */
export async function detectBillingTriggers(db, projectId, before, after) {
  const triggers = [];
  const now = new Date();
  const col = db.collection(DM_COLLECTIONS.billingTriggers);

  const prevPct = before?.collectionsPct || 0;
  const newPct = after?.collectionsPct || 0;
  const thresholds = [10, 30, 60, 90];

  for (const t of thresholds) {
    if (prevPct < t && newPct >= t) {
      const id = `trig_${projectId}_coll_${t}`;
      triggers.push({
        _id: id,
        projectId,
        triggerType: 'collection_threshold',
        thresholdPct: t,
        message: `Collections crossed ${t}% — review DM slab billing`,
        status: 'pending',
        createdAt: now
      });
    }
  }

  if (before?.revenueStatus !== after?.revenueStatus && after?.revenueStatus === 'collection_active') {
    triggers.push({
      _id: `trig_${projectId}_rev_active`,
      projectId,
      triggerType: 'revenue_status_change',
      message: 'Revenue status → collection_active — switch billing phase',
      status: 'pending',
      createdAt: now
    });
  }

  if (before?.latestKey !== after?.latestKey && after?.latestAchieved) {
    const m = after.latestAchieved;
    const id = `trig_${projectId}_ms_${m.key}`;
    triggers.push({
      _id: id,
      projectId,
      triggerType: 'construction_milestone',
      milestoneKey: m.key,
      cumDuePct: m.cumDuePct,
      achievedDate: m.achievedIso,
      message: `Construction milestone achieved: ${m.label} — review DM billing`,
      status: 'pending',
      createdAt: now
    });
    await emitNotification(db, {
      _id: `ntf_${id}`,
      type: 'construction_milestone',
      severity: 'high',
      projectId,
      title: `Milestone: ${m.label}`,
      detail: `Achieved ${m.achievedIso || '—'} · ${m.cumDuePct}% cumulative CLP`,
      href: `/app/dm-governance/projects/${projectId}`
    });
  }

  for (const t of triggers) {
    await col.updateOne({ _id: t._id }, { $set: t }, { upsert: true });
  }

  return triggers;
}
