/** Map stored status strings → visual tones. Do not rename stored values. */
export const STATUS_TONE = {
  live: 'live',
  completed: 'live',
  done: 'live',
  paid: 'live',
  approved: 'live',
  active: 'live',
  success: 'live',
  beta: 'beta',
  draft: 'beta',
  pending: 'orange',
  inprogress: 'orange',
  'in progress': 'orange',
  overdue: 'orange',
  risk: 'orange',
  failed: 'orange',
  error: 'orange',
  locked: 'locked',
  paused: 'locked',
  inactive: 'locked',
  notstarted: 'navy',
  'not started': 'navy',
  open: 'navy',
  default: 'beta',
};
